server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force-response: true
      force: true

spring:
  application:
    name: loa_back

  datasource:
    url: jdbc:mysql://localhost:3306/character_db
    username: root
    password: 31215
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

openapi:
  key: ${OPEN_API_KEY}
  url: https://developer-lostark.game.onstove.com
